### ISSUE TITLE
docker container does not run

### ISSUE THREAD

**Issue by RobertBerger** [akbennett/lava-docker#24]
```
./docker_run.sh reslocal/lava-docker enp3s0
+ ID_TO_KILL=$(docker ps -a -q  --filter ancestor=reslocal/lava-docker)
+ docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                          PORTS               NAMES
5a07fb45d087        reslocal/lava-docker   "/bin/sh -c '/star..."   About a minute ago   Exited (1) About a minute ago                       lava-docker
+ docker stop 5a07fb45d087
5a07fb45d087
+ docker rm -f 5a07fb45d087
5a07fb45d087
+ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
+ ID=$(sudo docker run -it -v /boot:/boot -v /lib/modules:/lib/modules -v /home/student/docker/lava-docker/local_scripts/fileshare:/opt/fileshare -v /dev/bus/u
sb:/dev/bus/usb -v /PATH/TO/id_rsa_lava.pub:/home/lava/.ssh/authorized_keys:ro --device=/dev/ttyUSB0 -p 8000:80 -p 2022:22 -h lava-docker --name lava-docker --
privileged reslocal/lava-docker)
+ ID Starting postgresql
[ ok ] Starting PostgreSQL 9.4 database server: main.  
Starting apache2
[....] Starting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerNa
me' directive globally to suppress this message
. ok 
Starting lava-server-gunicorn
[ ok ] Starting lava-server gunicorn wsgi support : lava-server-gunicorn.
Starting lava-server
lava-server appears to be running
Starting lava-master
[ ok ] Starting lava-server manage dispatcher-master : lava-master.
Starting lava-slave
[ ok ] Starting lava-slave : lava-slave.
Waiting for lavaserver database to be active
...
[ ok ] LAVA server ready
[ ok ] Reloading web server: apache2.
Unknown command: 'pipeline-worker'
Type 'lava-server help' for usage.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    82    0     0  100    82      0    157 --:--:-- --:--:-- --:--:--   157
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0     0  100   125      0   1108 --:--:-- --:--:-- --:--:--  1106
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19422    0 19256  100   166  76277    657 --:--:-- --:--:-- --:--:-- 76412
Unknown command: 'device-dictionary'
Type 'lava-server help' for usage.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19274    0 19108  100   166   281k   2507 --:--:-- --:--:-- --:--:--  282k
Unknown command: 'device-dictionary'
Type 'lava-server help' for usage.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    82    0     0  100    82      0   1224 --:--:-- --:--:-- --:--:--  1242
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0     0  100   124      0   3792 --:--:-- --:--:-- --:--:--  3875
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19418    0 19269  100   149   153k   1213 --:--:-- --:--:-- --:--:--  154k
Skipping hard_reset_command for kvm-1
Skipping connection_command for kvm-1
Installed 2 object(s) from 1 fixture(s)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19271    0 19122  100   149   228k   1822 --:--:-- --:--:-- --:--:--  230k
Skipping hard_reset_command for kvm-2
Skipping connection_command for kvm-2
Installed 2 object(s) from 1 fixture(s)
Submitting test job to LAVA server
Submitting test job to LAVA server
Traceback (most recent call last):
  File "/home/lava/bin/submityaml.py", line 110, in <module>
    process()
  File "/home/lava/bin/submityaml.py", line 104, in process
    jobid = submitJob(yamlfile, server)
  File "/home/lava/bin/submityaml.py", line 53, in submitJob
    jobid = server.scheduler.submit_job(yamlfile)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 400: "Problem with submitted job data: Invalid character for dictionary value @ data['actions'][2]['test']['monitors'][0]['name']">

```

**Comment by RobertBerger** [comment]
After some hacking in the dockerfile I got it to run:

```
 CMD /start.sh \
  && /home/lava/bin/add-qemu-to-lava.sh 2 \
  && /home/lava/bin/add-kvm-to-lava.sh 2 \
- && /home/lava/bin/submit.py -k /home/lava/bin/apikey.txt /home/lava/bin/kvm-basic.json \
- && /home/lava/bin/submityaml.py -k /home/lava/bin/apikey.txt /home/lava/bin/job1.yaml \
  && bash
+
+# don't want to submit any job just for fun (this would not give error but possiblt stuck the job queue
+# && /home/lava/bin/submit.py -k /home/lava/bin/apikey.txt /home/lava/bin/kvm-basic.json \
+# && bash
+
+# if we add this line it gets and error and freaks out:
+#&& /home/lava/bin/submityaml.py -k /home/lava/bin/apikey.txt /home/lava/bin/job1.yaml \
+#&& bash
+
```
